// <auto-generated />
using System;
using Backend.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(BackendDBContext))]
    [Migration("20240830124041_1.0")]
    partial class _10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.DbContext.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6cac9c5-2d86-4a02-9894-968d564bd5ad"),
                            IsAdmin = true,
                            Password = "password1",
                            UserName = "Test1"
                        },
                        new
                        {
                            Id = new Guid("2510519a-07c4-4ac1-a5e8-13a13bacd9a8"),
                            IsAdmin = false,
                            Password = "password2",
                            UserName = "Test2"
                        },
                        new
                        {
                            Id = new Guid("ea8838c5-fd63-474d-a10f-e9c8ce9ed88b"),
                            IsAdmin = false,
                            Password = "password3",
                            UserName = "Test3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
